package click.mafia42.payload;

public enum Commend {
    NOTHING,

    // SERVER
    DISCONNECT,
    SIGN_UP,
    SIGN_IN,
    REISSUE_TOKEN,
    CREATE_GAME_ROOM,
    JOIN_GAME_ROOM,
    FETCH_GAME_ROOMS,
    FETCH_USER_INFO_MYSELF,
    EXIT_GAME_ROOM,

    // CLIENT
    CONSOLE_OUTPUT,
    SAVE_TOKEN,
    SAVE_GAME_ROOM,
    SAVE_GAME_ROOM_LIST,
    SAVE_USER_INFO_MYSELF,
    REMOVE_GAME_ROOM;
}
